AuthedKafbat: Make healthchecks kinder to local logs

diff --git a/GetStarted/MultiBrokerClusterWithAuthAndMtls/AuthedKafkaUI/docker-compose.yaml b/GetStarted/MultiBrokerClusterWithAuthAndMtls/AuthedKafkaUI/docker-compose.yaml
--- a/GetStarted/MultiBrokerClusterWithAuthAndMtls/AuthedKafkaUI/docker-compose.yaml
+++ b/GetStarted/MultiBrokerClusterWithAuthAndMtls/AuthedKafkaUI/docker-compose.yaml
@@ -12,6 +12,7 @@ services:
       - apps_network
     ports:
       - 8088:8088
+      - 9000:9000 # For health checks, should resolve at http://localhost:9000/health and http://localhost:9000/health/ready
     stop_grace_period: 0s # SIGKILL after 0s during shutdown (no need for grace for this one)
     environment:
       KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
@@ -19,6 +20,7 @@ services:
       KEYCLOAK_ADMIN: "admin"
       KEYCLOAK_ADMIN_PASSWORD: "password"
       KC_HEALTH_ENABLED: "true"
+      KC_METRICS_ENABLED: "true"
       KC_LOG_LEVEL: "INFO"
       KC_HTTP_PORT: "8088"
       KC_HTTP_HOST: 0.0.0.0
@@ -323,18 +325,18 @@ services:
           then ehco 'Healthcheck file indication startup config done not created yet';
           exit 1;
           fi;
-          exec 3<>/dev/tcp/127.0.0.1/9000;
-          echo -e 'GET /health/ready HTTP/1.1\nhost: http://localhost/auth\nConnection: close\n\n' >&3;
-          if [ $? -eq 0 ];
-          then echo 'Healthcheck Web Endpoint Successful';
-          exit 0;
-          else echo 'Healthcheck Failed';
-          exit 1;
-          fi;
-      start_period: "15s"
-      interval: 30s
-      timeout: 10s
-      retries: 3
+        # exec 3<>/dev/tcp/127.0.0.1/9000;
+        # echo -e 'GET /health/ready HTTP/1.1\nhost: http://localhost\nConnection: close\n\n' >&3;
+        # if [ $? -eq 0 ];
+        # then echo 'Healthcheck Web Endpoint Successful';
+        # exit 0;
+        # else echo 'Healthcheck Failed';
+        # exit 1;
+        # fi;
+      start_period: "25s"
+      interval: 5s
+      timeout: 3s
+      retries: 10
 
   kafka-ui-authed:
     # image: ghcr.io/kafbat/kafka-ui
